### ISSUE TITLE
Ensure module uses aws_s3_bucket_acl resource

### ISSUE THREAD

**Issue by davidh-unmind** [terraform-aws-modules/terraform-aws-s3-bucket#140] opened 2022-03-29 07:53 UTC
Simple one really.

```
│ Warning: Argument is deprecated
│
│   with module.s3_bucket.aws_s3_bucket.this,
│   on main.tf line 5, in resource "aws_s3_bucket" "this":
│    5: resource "aws_s3_bucket" "this" {
│
│ Use the aws_s3_bucket_acl resource instead
│
│ (and 10 more similar warnings elsewhere)
```

**Comment by vutny** [comment] 2022-03-29 08:40
> (and 10 more similar warnings elsewhere)
Not that simple I would say. See here, there's a lot of deprecated arguments:
https://registry.terraform.io/providers/hashicorp/aws/3.75.0/docs/resources/s3_bucket

It means almost entire module has to be rewritten using new resources.

**Comment by davidh-unmind** [comment] 2022-03-29 08:49
Indeed there is. That's a bit of scope creep. My issue did not say address all warnings. Fixing the issues warning should be easy enough.

**Comment by antonbabenko** [comment] 2022-03-29 09:02
Closing as duplicate of #139

**Closed by antonbabenko** 2022-03-29 09:02 UTC
